# Generated by Django 4.2.8 on 2025-12-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Жанр')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-идентификатор')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'movies_genre',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration', models.IntegerField(help_text='Сколько минут длится фильм', verbose_name='Длительность (в минутах)')),
                ('release_year', models.IntegerField(verbose_name='Год выпуска')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='От 0.0 до 10.0', max_digits=3, verbose_name='Рейтинг')),
                ('poster_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на постер')),
                ('genres', models.ManyToManyField(help_text='К каким жанрам относится фильм', related_name='movies', to='movies.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-release_year', 'title'],
            },
        ),
    ]
