# Generated by Django 4.2.8 on 2025-12-22 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_mood', models.CharField(max_length=100, verbose_name='Выбранное настроение')),
                ('available_time', models.IntegerField(verbose_name='Доступное время (минуты)')),
                ('search_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время поиска')),
                ('matched_movies', models.ManyToManyField(to='movies.movie', verbose_name='Подобранные фильмы')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История подбора',
                'verbose_name_plural': 'Истории подборов',
                'ordering': ['-search_timestamp'],
            },
        ),
    ]
