# Generated by Django 4.2.8 on 2026-01-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_duration_alter_movie_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, help_text='Уникальный идентификатор фильма в базе IMDb', max_length=20, null=True, unique=True, verbose_name='IMDb ID'),
        ),
    ]
